version: '3.8'
services:
  db:
    container_name: "bdia-postgres"
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5435:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/docker-init.sql:/docker-entrypoint-initdb.d/docker-init.sql